AWSTemplateFormatVersion: '2010-09-09'
Description: AWS SAM template with API defined in an external Swagger file along with
  Lambda integrations and CORS configurations
Outputs:
  ApiUrl:
    Description: URL of your API endpoint
    Value:
      Fn::Join:
      - ''
      - - https://
        - Ref: ApiGatewayApi
        - .execute-api.
        - Ref: AWS::Region
        - .amazonaws.com/Prod
Parameters:
  BucketName:
    Default: aws-lambda-nr-postdeploy
    Type: String
  NRLicenseKey:
    Type: String
Resources:
  ApiGatewayApi:
    Properties:
      Cors: '''*'''
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location:
              Fn::Sub: s3://${BucketName}/swagger.yml
      StageName: Prod
    Type: AWS::Serverless::Api
  LambdaFunction:
    Properties:
      CodeUri: s3://aws-lambda-nr-postdeploy/78fb084d63587d08896d72e54fe10edc
      Events:
        ProxyApiRoot:
          Properties:
            Method: ANY
            Path: /
            RestApiId:
              Ref: ApiGatewayApi
          Type: Api
      Handler: index.handler
      Runtime: nodejs6.10
      Timeout: 30
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
