AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Lambda + AWS API Gateway + Express + New Relic Browser
Outputs:
  ApiUrl:
    Description: URL of your API endpoint
    Value:
      Fn::Join:
      - ''
      - - https://
        - Ref: ApiGatewayApi
        - .execute-api.
        - Ref: AWS::Region
        - .amazonaws.com/Prod
Parameters:
  BucketName:
    Default: aws-lambda-nr-postdeploy
    Type: String
  NRAccountId:
    Type: String
  NRInsightsQueryKey:
    Type: String
Resources:
  ApiGatewayApi:
    Properties:
      Cors: '''*'''
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location:
              Fn::Sub: s3://${BucketName}/swagger.yaml
      StageName: Prod
    Type: AWS::Serverless::Api
  LambdaFunction:
    Properties:
      AutoPublishAlias: live
      CodeUri: s3://aws-lambda-nr-postdeploy/300fa4e287a0ad79c9e4b006fa3d3395
      DeploymentPreference:
        Hooks:
          PostTraffic:
            Ref: PostTrafficHookFunction
        Type: AllAtOnce
      Events:
        Greeting:
          Properties:
            Method: ANY
            Path: /greeting
            RestApiId:
              Ref: ApiGatewayApi
          Type: Api
        ProxyApiRoot:
          Properties:
            Method: ANY
            Path: /
            RestApiId:
              Ref: ApiGatewayApi
          Type: Api
      Handler: index.handler
      MemorySize: 512
      Runtime: nodejs6.10
      Timeout: 30
    Type: AWS::Serverless::Function
  PostTrafficHookFunction:
    Properties:
      CodeUri: s3://aws-lambda-nr-postdeploy/8604f0685ac59a9852e41f4693988f04
      DeploymentPreference:
        Enabled: false
      Environment:
        Variables:
          CurrentVersion:
            Ref: LambdaFunction.Version
          NEWRELIC_ACCOUNT_ID:
            Ref: NRAccountId
          NEWRELIC_INSIGHTS_QUERY_KEY:
            Ref: NRInsightsQueryKey
      FunctionName: CodeDeployHook_postTrafficHook
      Handler: index.handler
      Policies:
      - Statement:
        - Action:
          - codedeploy:PutLifecycleEventHookExecutionStatus
          Effect: Allow
          Resource:
            Fn::Sub: arn:aws:codedeploy:${AWS::Region}:${AWS::AccountId}:deploymentgroup:${ServerlessDeploymentApplication}/*
        Version: '2012-10-17'
      - Statement:
        - Action:
          - lambda:InvokeFunction
          Effect: Allow
          Resource:
            Ref: LambdaFunction.Version
        Version: '2012-10-17'
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
  SyntheticTrafficFunction:
    Properties:
      CodeUri: s3://lambdium-upload-bucket/4fcc083b4f8302daf6c68d19001d8c8d
      Environment:
        Variables:
          PAGE_URL:
            Fn::Join:
            - ''
            - - https://
              - Ref: ApiGatewayApi
              - .execute-api.
              - Ref: AWS::Region
              - .amazonaws.com/Prod
      Events:
        CheckWebsiteScheduledEvent:
          Properties:
            Schedule: rate(1 minute)
          Type: Schedule
        CheckWebsiteScheduledEvent2:
          Properties:
            Schedule: rate(1 minute)
          Type: Schedule
        CheckWebsiteScheduledEvent3:
          Properties:
            Schedule: rate(1 minute)
          Type: Schedule
      Handler: index.handler
      MemorySize: 1154
      Runtime: nodejs6.10
      Timeout: 25
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
