
---
swagger: 2.0
basePath: /prod
info:
  title: AwsSamExample
schemes:
  - https
paths:
  /:
    x-amazon-apigateway-any-method:
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          schema:
            $ref: "#/definitions/Empty"
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: 200
        # NOTE: ${LambdaFunction} must match the Lambda resourcename. This uses the 'live' function alias.
        uri: 
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFunction.Arn}:live/invocations"

        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
  /greeting:
    x-amazon-apigateway-any-method:
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          schema:
            $ref: "#/definitions/Empty"
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: 200
        # NOTE: ${LambdaFunction} must match the Lambda resourcename. This uses the 'live' function alias.
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFunction.Arn}:live/invocations"

        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
definitions:
  Empty:
    type: object
    title: Empty Schema